// src/components/InfoTableRow.jsx
import React, { useMemo } from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';

function InfoTableRow({
  title, value, valueColor, alignRight,
}) {
  const dataClass = useMemo(() => classNames({
    'font-monospace': true,
    'text-end': alignRight,
  }), [alignRight]);

  const valueCellStyle = useMemo(() => {
    const style = {};

    if (valueColor !== '') {
      style.color = valueColor;
    }

    return style;
  }, [valueColor]);

  return (
    <tr>
      <td className="fw-bold">{title}</td>
      <td className={dataClass} style={valueCellStyle}>{value}</td>
    </tr>
  );
}

InfoTableRow.propTypes = {
  title: PropTypes.string.isRequired,
  value: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  alignRight: PropTypes.bool,
  valueColor: PropTypes.string,
};

InfoTableRow.defaultProps = {
  alignRight: false,
  value: '',
  valueColor: '',
};

export default InfoTableRow;

// components/InfoTableRow.vue
<template lang="pug">
tr
  td.fw-bold
    slot(name="title", :title="title") {{ title }}
  td(:class="dataClass", :style="valueCellStyle")
    slot(name="value", :value="value") {{ value }}
</template>

<script setup lang="ts">
import type { StyleValue } from "vue";

const props = withDefaults(
  defineProps<{
    title: string;
    value?: string | number;
    valueColor?: string;
    alignRight?: boolean;
  }>(),
  {
    value: "",
    alignRight: false,
  }
);

const dataClass = computed(() => ({
  "font-monospace": true,
  "text-end": props.alignRight,
}));

const valueCellStyle = computed(() => {
  const style: StyleValue = {};

  if (props.valueColor) {
    style.color = props.valueColor;
  }

  return style;
});
</script>
